# Server configuration
server:
  port: 801
  servlet.context-path: /jpa
    
# See http://docs.spring.io/spring-boot/docs/1.2.1.RELEASE/reference/htmlsingle/#boot-features-custom-log-levels
logging:
  level:
    org.springframework: INFO
    bcp.spring: DEBUG

# Configuring info endpoint
info:
  app:
    name: Spring JPA Sample Application
    description: Test JPA Application
    version: 1.0.0